# Generated by Django 5.2.10 on 2026-03-06 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sereneapp', '0008_advanceddepressionprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldoctorfeedback',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sereneapp.hospitalbooking'),
        ),
        migrations.AddField(
            model_name='hospitaldoctorfeedback',
            name='tension_free_level',
            field=models.IntegerField(default=0),
        ),
    ]
